version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "nutrition-tracker-api"
s3_bucket = "nutrition-tracker-sam-bucket-1762413523"
s3_prefix = "nutrition-tracker-api"
region = "ap-south-1"
capabilities = "CAPABILITY_IAM"
